### ISSUE TITLE
Does SafeResourceLoader support custom resources?

### ISSUE THREAD

**Issue by Loppansson** [derkork/godot-safe-resource-loader#2]
Hi! First, thanks for taking the time creating this add-on; it's very appreciated!:D Second, i'm wondering if the SafeResourceLoader supports custom resources? I'm able to save and load built-in resources without any problem, but i'm not having any luck with custom resources^^'

**Code:**
![image](https://github.com/derkork/godot-safe-resource-loader/assets/61879422/2567c277-e3ba-4c46-8165-d7418e880265)

**Output:**
![image](https://github.com/derkork/godot-safe-resource-loader/assets/61879422/2db2afbb-8aab-4202-9474-eddf0fad1cf0)

(The modified albedo_color property is saved and loaded, but not the id property.)

**Custom Resource Code:**
![image](https://github.com/derkork/godot-safe-resource-loader/assets/61879422/4ab6fea1-8915-407d-a24d-f598bb79477e)

**Comment by derkork** [comment]
You need to add an `@export` to your `id` variable,  otherwise Godot will not export or import it.  

```gdscript
@export var id:int = 0 
```

**Comment by Loppansson** [comment]
That fixed it! Thank you:)
